arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0005
  kinematics_solver_timeout: 10.0
  kinematics_solver_attempts: 30000
  position_only_ik: True
